version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./src:/myfolder/src
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev

  # database:
  #   platform: linux/x86_64
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: "mydocker"
  #     MYSQL_ROOT_PASSWORD: "root"
  #   ports:
  #     - 3306:3306




  # database:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.mongo
  #   ports:
  #     - 27017:27017